name: CI

# Trigger the workflow on push or pull request
on: [ push, pull_request ]

jobs:
  prepare-sha:
    runs-on: ubuntu-latest
    steps:
      - run: echo "null"
    outputs:
      sha: ${{ github.sha }}

  test-latest:
    needs: prepare-sha
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
      fail-fast: false
    name: "Test latest ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Download BSC
        id: download
        uses: B-Lang-org/download-bsc@${{ needs.prepare-sha.sha }}
        with:
          os: ${{ matrix.os }}
          version: latest
          path: ../

      - name: Build
        run: |
          echo Version tag: ${{steps.download.outputs.tag}}
          echo Version hash: ${{steps.download.outputs.commit}}
          export PATH=$PWD/../bsc/bin:$PATH
          bsc -v

  test-release:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
      fail-fast: false
    name: "Test release ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Download BSC
        id: download
        uses: B-Lang-org/download-bsc@v1
        with:
          os: ${{ matrix.os }}
          version: 2023.07
          path: ../

      - name: Build
        run: |
          echo Version tag: ${{steps.download.outputs.tag}}
          echo Version hahs: ${{steps.download.outputs.commit}}
          export PATH=$PWD/../bsc/bin:$PATH
          bsc -v
